### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by dschust-r** [haddocking/haddock2mmcif#2]
Dear Rodrigo and Alexandre, 

Thank you for providing a solution to convert the HADDOCK output into an mmcif file, this is really useful. 
I am currently preparing for a PDB-Dev submission and would like to encode my HADDOCK output in an mmcif file. 
Unfortunately, I am rather new to all of this and I am having troubles running the haddock2mmcif script. 
The problem might be the installation of python and VSCode on my computer but I am not 100% sure. 
The installation of haddock2mmcif seems to have worked properly but I can't seem to use the haddock2mmcif command directly in VSCode. 

So when I run it with `C:\Users\dschuster\Scripts\haddock2mmcif.exe --output example.cif E2A-HPR/ `
I get the following output: 

> 2023-06-06 10:43:19,157 cli:140 INFO - Input run directory: E2A-HPR
>  2023-06-06 10:43:19,157 cli:145 INFO - Initializing System
>  2023-06-06 10:43:19,157 cli:153 INFO - Creating Asymetric Units
>  2023-06-06 10:43:19,158 cli:161 INFO - Reading E2A-HPR\begin\complex_1.pdb
>  2023-06-06 10:43:19,168 cli:168 INFO - Creating entity based on chain A
>  2023-06-06 10:43:19,168 cli:168 INFO - Creating entity based on chain B
>  2023-06-06 10:43:19,169 cli:180 INFO - Adding Asymetric Units to the System
>  2023-06-06 10:43:19,169 cli:186 INFO - Organizing Asymetric Units into Modeled Assembly
>  2023-06-06 10:43:19,169 cli:191 INFO - Defining the protocol
>  2023-06-06 10:43:19,169 cli:201 INFO - Ranking the clusters from E2A-HPR\structures\it1\water\analysis\cluster.out based on E2A-HPR\structures\it1\water\file.list
>  2023-06-06 10:43:19,180 cli:208 INFO - Getting the interface cutoff from E2A-HPR\run.cns
>  2023-06-06 10:43:19,194 cli:216 INFO - Processing cluster1_1.pdb
> Traceback (most recent call last):
>   File "C:\Users\dschuster\Scripts\haddock2mmcif-script.py", line 33, in <module>
>     sys.exit(load_entry_point('haddock2mmcif', 'console_scripts', 'haddock2mmcif')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\users\dschuster\haddock2mmcif\src\haddock2mmcif\cli.py", line 225, in main
>     cluster_pdb.get_interface(cutoff=interface_cutoff)
>   File "c:\users\dschuster\haddock2mmcif\src\haddock2mmcif\modules\pdb.py", line 82, in get_interface
>     out = subprocess.check_output(shlex.split(cmd))  # nosec
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dschuster\Lib\subprocess.py", line 466, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dschuster\Lib\subprocess.py", line 548, in run
>     with Popen(*popenargs, **kwargs) as process:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dschuster\Lib\subprocess.py", line 1024, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\dschuster\Lib\subprocess.py", line 1509, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 2] The system cannot find the file specified

Do you maybe have any idea what could be wrong on my side? I would be thankful for any and all help and guidance. Really trying to get this mmcif file ready for our submission 😄 

Thank you and all the best, 
Dina

**Comment by rvhonorato** [comment]
Thanks for reaching out about this issue! Based on your logs it seems that its coming from this part of the code:

https://github.com/haddocking/haddock2mmcif/blob/3fdd4ffb229b0e2c68fba1897b9de93b0c2a0d4b/src/haddock2mmcif/modules/pdb.py#L81-L82

`contact-chainID` is a c++ binary compiled for linux, and based on your folder structure you seems to be using windows without WSL. I'd suggest you try configuring WSL and VSCode and trying again, all the information is here: https://code.visualstudio.com/docs/remote/wsl#_getting-started

**Comment by dschust-r** [comment]
Thank you for your reply and help! This already helped a lot, I can now start to process the example data correctly. 
When I start to process my own data, however, it gets stuck after a few clusters with the message:

> Traceback (most recent call last):
>   File "/usr/local/bin/haddock2mmcif", line 33, in <module>
>     sys.exit(load_entry_point('haddock2mmcif', 'console_scripts', 'haddock2mmcif')())
>   File "/mnt/c/Users/dschuster/haddock2mmcif/src/haddock2mmcif/cli.py", line 215, in main
>     for structure in clustered_structures[cluster_name]:
> KeyError: 5

My HADDOCK output contains 10 clusters: 1, 2, 3, 4, 6, 8, 9, 14, 15, 16

Edit: I tried to run it with a different HADDOCK output folder and got the same issue after cluster rank 7. A colleague of mine also tried to run it and got the same error.

**Comment by rvhonorato** [comment]
Glad you could set it up! 

Ok this one looks more like a proper bug, I'll close this issue since your initial query was solved - could you please open a new issue as a bug report and fill in the fields? https://github.com/haddocking/haddock2mmcif/issues/new/choose
