### ISSUE TITLE
haddock2mmcif stops without output after 7 clusters

### ISSUE THREAD

**Issue by dschust-r** [haddocking/haddock2mmcif#3]
**Describe the bug**
Conversion pipeline stops after the seven highest ranked clusters, no output file is generated. 
The bug can be reproduced by different people, as well as when using a different HADDOCK output folder for the conversion.

Last few lines before error: 
>  2023-06-06 15:31:47,910 cli:216 INFO - Processing cluster3_1.pdb
>  2023-06-06 15:31:48,587 cli:216 INFO - Processing cluster3_2.pdb
>  2023-06-06 15:31:49,264 cli:216 INFO - Processing cluster3_3.pdb
>  2023-06-06 15:31:49,941 cli:216 INFO - Processing cluster3_4.pdb
>  2023-06-06 15:31:50,619 cli:256 INFO - Finalizing group cluster Rank: 7 Number:3

Error message: 
> Traceback (most recent call last):
>   File "/usr/local/bin/haddock2mmcif", line 33, in <module>
>     sys.exit(load_entry_point('haddock2mmcif', 'console_scripts', 'haddock2mmcif')())
>   File "/mnt/c/Users/dschuster/haddock2mmcif/src/haddock2mmcif/cli.py", line 215, in main
>     for structure in clustered_structures[cluster_name]:
> KeyError: 5

**To Reproduce**
https://wenmr.science.uu.nl/haddock2.4/run/6879610780/129967-AC8-Gbg_2 
I am not sure if this run can still be found - I would otherwise also be happy to share the files in a different way

**Expected behavior**
Expected haddock2mmcif to convert HADDOCK output to mmcif file.

**Additional context**
My output has 10 clusters (cluster 1, 2, 3, 4, 6, 8, 9, 14, 15, 16)

**Comment by rvhonorato** [comment]
Thanks for opening the issue, could you please send the `job_params.json` found inside the run directory to rvhonorato@protonmail.com?

**Comment by rvhonorato** [comment]
thanks very much for reporting this @dschust-r, it revealed some underlying issues that were hopefully fixed with #5. 

Please try again with the updated version: `git checkout main && git pull` !
